version: "1.0"
info:
  model: int-scaffold
packages:
- name: Serengeti_GithubProject
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: substractpackage
  version: "1.0"
  gitServerName: srcCtrl_gitlab_Arti
  gitUrl: https://gitlab.com/ArtiKhareGitlabnew
  gitUsername: ArtiKhareGitlabnew
  gitBranch: master
- name: AddIntsPackage
  version: "1.0"
  gitServerName: srcCtrl_AzRepos_Arti_IBM
  gitUrl: https://dev.azure.com/ArtiKhare/AddIntsPackage/_git
  gitUsername: ArtiKhare
  gitBranch: master
- name: LowerFSPackage
  version: "1.0"
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: InvalidPackage
  version: "1.0"
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
services:
- serviceName: project.serengeti_github.integrations:Copy_lowerfspkg_fs
  packages:
  - name: Serengeti_GithubProject
    version: "1.0"
  - name: AddIntsPackage
    version: "1.0"
  - name: substractpackage
    version: "1.0"
  - name: LowerFSPackage
    version: "1.0"
  - name: InvalidPackage
    version: "1.0"
- serviceName: LowerFSPackage:lowerFS
  packages:
  - name: LowerFSPackage
    version: "1.0"
- serviceName: pub.string:toLower
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
- serviceName: project.serengeti_github.integrations:FSDFS
  packages:
  - name: Serengeti_GithubProject
    version: "1.0"
  - name: AddIntsPackage
    version: "1.0"
  - name: substractpackage
    version: "1.0"
  - name: LowerFSPackage
    version: "1.0"
  - name: InvalidPackage
    version: "1.0"
- serviceName: AddIntsPackage:addIntsFS
  packages:
  - name: AddIntsPackage
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
- serviceName: project.serengeti_github.integrations:UntitledVFDV
  packages:
  - name: Serengeti_GithubProject
    version: "1.0"
  - name: AddIntsPackage
    version: "1.0"
  - name: substractpackage
    version: "1.0"
  - name: LowerFSPackage
    version: "1.0"
  - name: InvalidPackage
    version: "1.0"
- serviceName: SubstractPackage:substractFS
  packages:
  - name: substractpackage
    version: "1.0"
- serviceName: pub.math:subtractInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
- serviceName: project.serengeti_github.integrations:gcd_github
  packages:
  - name: Serengeti_GithubProject
    version: "1.0"
  - name: AddIntsPackage
    version: "1.0"
  - name: substractpackage
    version: "1.0"
  - name: LowerFSPackage
    version: "1.0"
  - name: InvalidPackage
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
- serviceName: project.serengeti_github.integrations:lowerfspkg_fs
  packages:
  - name: Serengeti_GithubProject
    version: "1.0"
  - name: AddIntsPackage
    version: "1.0"
  - name: substractpackage
    version: "1.0"
  - name: LowerFSPackage
    version: "1.0"
  - name: InvalidPackage
    version: "1.0"
