version: "1.0"
info:
  model: int-scaffold
packages:
- name: Serengeti_GithubProject
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
services:
- serviceName: project.serengeti_github.integrations:gcd_github
  packages:
  - name: Serengeti_GithubProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2043
